// Generated by Wrangler on Sun May 26 2024 17:03:05 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  AUTH_SECRET: string;
  R2_ENDPOINT: string;
  R2_ACCESS_ID: string;
  R2_SECRET_KEY: string;
  R2_BUCKET_NAME: string;
  BACKEND_SECURITY_KEY: string;
  STORAGE: R2Bucket;
  DATABASE: D1Database;
}
