// Generated by Wrangler on Thu Jul 25 2024 01:03:57 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CANVAS_SNAPS: KVNamespace;
	RECOMMENDATIONS: KVNamespace;
	AUTH_URL: string;
	AUTH_SECRET: string;
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	DATABASE_URL: string;
	BACKEND_SECURITY_KEY: string;
	BACKEND_BASE_URL: string;
	STORAGE: R2Bucket;
	DATABASE: D1Database;
	DEV_IMAGES: R2Bucket;
	CANVAS_SNAPS: KVNamespace;
	AI: Ai;
}
