// Generated by Wrangler on Sun May 26 2024 17:03:05 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	STORAGE: R2Bucket;
	DATABASE: D1Database;
	DEV_IMAGES: R2Bucket;
	CANVAS_SNAPS: KVNamespace;
	AI: Ai;
	RECOMMENDATIONS: KVNamespace;
}
