version: "3.8"

services:
    db:
        build: .
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=supermemory
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
