// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  RATELIMITER: RateLimitBinding;
}

export interface RateLimitBinding {
  limit: LimitFunc;
}

export interface LimitFunc {
  (options: LimitOptions): Promise<RateLimitResult>;
}

interface RateLimitResult {
  success: boolean;
}

export interface LimitOptions {
  key: string;
}

export interface RateLimitResponse {
  key: string;
  success: boolean;
}

export interface RateLimitOptions {
  continueOnRateLimit: boolean;
}

export type RateLimitKeyFunc = {
  (c: Context): string;
};

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      // [key: string]: string | undefined;
      RATELIMITER: RateLimitBinding;
      CLOUDFLARE_TURNSTILE_TOKEN: string;
    }
  }
}

export {};
